SciErr (* getMatrixOfDouble) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,double **_pdblReal);
SciErr (* getComplexMatrixOfDouble) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,double **_pdblReal,double **_pdblImg);
SciErr (* getComplexZMatrixOfDouble) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,doublecomplex **_pdblZ);
SciErr (* allocMatrixOfDouble) (void *_pvCtx,int _iVar,int _iRows,int _iCols,double **_pdblReal);
SciErr (* allocComplexMatrixOfDouble) (void *_pvCtx,int _iVar,int _iRows,int _iCols,double **_pdblReal,double **_pdblImg);
SciErr (* createMatrixOfDouble) (void *_pvCtx,int _iVar,int _iRows,int _iCols,double const *_pdblReal);
SciErr (* createComplexMatrixOfDouble) (void *_pvCtx,int _iVar,int _iRows,int _iCols,double const *_pdblReal,double const *_pdblImg);
SciErr (* createComplexZMatrixOfDouble) (void *_pvCtx,int _iVar,int _iRows,int _iCols,doublecomplex const *_pdblData);
SciErr (* createNamedMatrixOfDouble) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,double const *_pdblReal);
SciErr (* createNamedComplexMatrixOfDouble) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,double const *_pdblReal,double const *_pdblImg);
SciErr (* createNamedComplexZMatrixOfDouble) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,doublecomplex const *_pdblData);
SciErr (* readNamedMatrixOfDouble) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,double *_pdblReal);
SciErr (* readNamedComplexMatrixOfDouble) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,double *_pdblReal,double *_pdblImg);
int (* isDoubleType) (void *_pvCtx,int *_piAddress);
int (* isNamedDoubleType) (void *_pvCtx,char const *_pstName);
int (* getScalarDouble) (void *_pvCtx,int *_piAddress,double *_pdblReal);
int (* getScalarComplexDouble) (void *_pvCtx,int *_piAddress,double *_pdblReal,double *_pdblImg);
int (* getNamedScalarDouble) (void *_pvCtx,char const *_pstName,double *_pdblReal);
int (* getNamedScalarComplexDouble) (void *_pvCtx,char const *_pstName,double *_pdblReal,double *_pdblImg);
int (* createScalarDouble) (void *_pvCtx,int _iVar,double _dblReal);
int (* createScalarComplexDouble) (void *_pvCtx,int _iVar,double _dblReal,double _dblImg);
int (* createNamedScalarDouble) (void *_pvCtx,char const *_pstName,double _dblReal);
int (* createNamedScalarComplexDouble) (void *_pvCtx,char const *_pstName,double _dblReal,double _dblImg);
SciErr (* getMatrixOfString) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piLength,char **_pstStrings);
SciErr (* getMatrixOfWideString) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piwLength,wchar_t **_pwstStrings);
SciErr (* createMatrixOfString) (void *_pvCtx,int _iVar,int _iRows,int _iCols,char const *const *_pstStrings);
SciErr (* createMatrixOfWideString) (void *_pvCtx,int _iVar,int _iRows,int _iCols,wchar_t const *const *_pwstStrings);
SciErr (* createNamedMatrixOfString) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,char const *const *_pstStrings);
SciErr (* createNamedMatrixOfWideString) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,wchar_t const *const *_pwstStrings);
SciErr (* readNamedMatrixOfString) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piLength,char **_pstStrings);
SciErr (* readNamedMatrixOfWideString) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piwLength,wchar_t **_pwstStrings);
int (* isStringType) (void *_pvCtx,int *_piAddress);
int (* isNamedStringType) (void *_pvCtx,char const *_pstName);
int (* getAllocatedSingleString) (void *_pvCtx,int *_piAddress,char **_pstData);
int (* getAllocatedSingleWideString) (void *_pvCtx,int *_piAddress,wchar_t **_pwstData);
int (* getAllocatedMatrixOfString) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,char ***_pstData);
int (* getAllocatedMatrixOfWideString) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,wchar_t ***_pwstData);
int (* getAllocatedNamedSingleString) (void *_pvCtx,char const *_pstName,char **_pstData);
int (* getAllocatedNamedSingleWideString) (void *_pvCtx,char const *_pstName,wchar_t **_pwstData);
int (* getAllocatedNamedMatrixOfString) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,char ***_pstData);
int (* getAllocatedNamedMatrixOfWideString) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,wchar_t ***_pwstData);
int (* createSingleString) (void *_pvCtx,int _iVar,char const *_pstStrings);
int (* createSingleWideString) (void *_pvCtx,int _iVar,wchar_t const *_pwstStrings);
int (* createNamedSingleString) (void *_pvCtx,char const *_pstName,char const *_pstStrings);
int (* createNamedSingleWideString) (void *_pvCtx,char const *_pstName,wchar_t const *_pwstStrings);
void (* freeAllocatedSingleString) (char *_pstData);
void (* freeAllocatedSingleWideString) (wchar_t *_pwstData);
void (* freeAllocatedMatrixOfString) (int _iRows,int _iCols,char **_pstData);
void (* freeAllocatedMatrixOfWideString) (int _iRows,int _iCols,wchar_t **_pwstData);
SciErr (* getMatrixOfIntegerPrecision) (void *_pvCtx,int *_piAddress,int *_piPrecision);
SciErr (* getMatrixOfInteger8) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,char **_pcData8);
SciErr (* getMatrixOfUnsignedInteger8) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,unsigned char **_pucData8);
SciErr (* getMatrixOfInteger16) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,short **_psData16);
SciErr (* getMatrixOfUnsignedInteger16) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,unsigned short **_pusData16);
SciErr (* getMatrixOfInteger32) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int **_piData32);
SciErr (* getMatrixOfUnsignedInteger32) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,unsigned int **_puiData32);
SciErr (* createMatrixOfInteger8) (void *_pvCtx,int _iVar,int _iRows,int _iCols,char const *_pcData8);
SciErr (* createMatrixOfUnsignedInteger8) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned char const *_pucData8);
SciErr (* createMatrixOfInteger16) (void *_pvCtx,int _iVar,int _iRows,int _iCols,short const *_psData16);
SciErr (* createMatrixOfUnsignedInteger16) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned short const *_pusData16);
SciErr (* createMatrixOfInteger32) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int const *_piData32);
SciErr (* createMatrixOfUnsignedInteger32) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned int const *_puiData32);
SciErr (* createNamedMatrixOfInteger8) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,char const *_pcData8);
SciErr (* createNamedMatrixOfUnsignedInteger8) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,unsigned char const *_pucData8);
SciErr (* createNamedMatrixOfInteger16) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,short const *_psData16);
SciErr (* createNamedMatrixOfUnsignedInteger16) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,unsigned short const *_pusData16);
SciErr (* createNamedMatrixOfInteger32) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,int const *_piData32);
SciErr (* createNamedMatrixOfUnsignedInteger32) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,unsigned int const *_puiData32);
SciErr (* allocMatrixOfInteger8) (void *_pvCtx,int _iVar,int _iRows,int _iCols,char **_pcData8);
SciErr (* allocMatrixOfUnsignedInteger8) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned char **_pucData8);
SciErr (* allocMatrixOfInteger16) (void *_pvCtx,int _iVar,int _iRows,int _iCols,short **_psData16);
SciErr (* allocMatrixOfUnsignedInteger16) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned short **_pusData16);
SciErr (* allocMatrixOfInteger32) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int **_piData32);
SciErr (* allocMatrixOfUnsignedInteger32) (void *_pvCtx,int _iVar,int _iRows,int _iCols,unsigned int **_puiData32);
SciErr (* getNamedMatrixOfIntegerPrecision) (void *_pvCtx,char const *_pstName,int *_piPrecision);
SciErr (* readNamedMatrixOfInteger8) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,char *_pcData8);
SciErr (* readNamedMatrixOfUnsignedInteger8) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,unsigned char *_pucData8);
SciErr (* readNamedMatrixOfInteger16) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,short *_psData16);
SciErr (* readNamedMatrixOfUnsignedInteger16) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,unsigned short *_pusData16);
SciErr (* readNamedMatrixOfInteger32) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piData32);
SciErr (* readNamedMatrixOfUnsignedInteger32) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,unsigned int *_puiData32);
int (* isIntegerType) (void *_pvCtx,int *_piAddress);
int (* isNamedIntegerType) (void *_pvCtx,char const *_pstName);
int (* getScalarInteger8) (void *_pvCtx,int *_piAddress,char *_pcData);
int (* getScalarUnsignedInteger8) (void *_pvCtx,int *_piAddress,unsigned char *_pucData);
int (* getScalarInteger16) (void *_pvCtx,int *_piAddress,short *_psData);
int (* getScalarUnsignedInteger16) (void *_pvCtx,int *_piAddress,unsigned short *_pusData);
int (* getScalarInteger32) (void *_pvCtx,int *_piAddress,int *_piData);
int (* getScalarUnsignedInteger32) (void *_pvCtx,int *_piAddress,unsigned int *_puiData);
int (* getNamedScalarInteger8) (void *_pvCtx,char const *_pstName,char *_pcData);
int (* getNamedScalarUnsignedInteger8) (void *_pvCtx,char const *_pstName,unsigned char *_pucData);
int (* getNamedScalarInteger16) (void *_pvCtx,char const *_pstName,short *_psData);
int (* getNamedScalarUnsignedInteger16) (void *_pvCtx,char const *_pstName,unsigned short *_pusData);
int (* getNamedScalarInteger32) (void *_pvCtx,char const *_pstName,int *_piData);
int (* getNamedScalarUnsignedInteger32) (void *_pvCtx,char const *_pstName,unsigned int *_puiData);
int (* createScalarInteger8) (void *_pvCtx,int _iVar,char _cData);
int (* createScalarUnsignedInteger8) (void *_pvCtx,int _iVar,unsigned char _ucData);
int (* createScalarInteger16) (void *_pvCtx,int _iVar,short _sData);
int (* createScalarUnsignedInteger16) (void *_pvCtx,int _iVar,unsigned short _usData);
int (* createScalarInteger32) (void *_pvCtx,int _iVar,int _iData);
int (* createScalarUnsignedInteger32) (void *_pvCtx,int _iVar,unsigned int _uiData);
int (* createNamedScalarInteger8) (void *_pvCtx,char const *_pstName,char _cData);
int (* createNamedScalarUnsignedInteger8) (void *_pvCtx,char const *_pstName,unsigned char _ucData);
int (* createNamedScalarInteger16) (void *_pvCtx,char const *_pstName,short _sData);
int (* createNamedScalarUnsignedInteger16) (void *_pvCtx,char const *_pstName,unsigned short _usData);
int (* createNamedScalarInteger32) (void *_pvCtx,char const *_pstName,int _iData);
int (* createNamedScalarUnsignedInteger32) (void *_pvCtx,char const *_pstName,unsigned int _uiData);
SciErr (* getPolyVariableName) (void *_pvCtx,int *_piAddress,char *_pstVarName,int *_piVarNameLen);
SciErr (* getMatrixOfPoly) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal);
SciErr (* getComplexMatrixOfPoly) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
SciErr (* createMatrixOfPoly) (void *_pvCtx,int _iVar,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal);
SciErr (* createComplexMatrixOfPoly) (void *_pvCtx,int _iVar,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal,double const *const *_pdblImg);
SciErr (* createNamedMatrixOfPoly) (void *_pvCtx,char const *_pstName,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal);
SciErr (* createNamedComplexMatrixOfPoly) (void *_pvCtx,char const *_pstName,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal,double const *const *_pdblImg);
SciErr (* readNamedMatrixOfPoly) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal);
SciErr (* readNamedComplexMatrixOfPoly) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
int (* isPolyType) (void *_pvCtx,int *_piAddress);
int (* isNamedPolyType) (void *_pvCtx,char const *_pstName);
int (* getAllocatedSinglePoly) (void *_pvCtx,int *_piAddress,int *_piNbCoef,double **_pdblReal);
int (* getAllocatedSingleComplexPoly) (void *_pvCtx,int *_piAddress,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
int (* getAllocatedNamedSinglePoly) (void *_pvCtx,char const *_pstName,int *_piNbCoef,double **_pdblReal);
int (* getAllocatedNamedSingleComplexPoly) (void *_pvCtx,char const *_pstName,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
int (* getAllocatedMatrixOfPoly) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int **_piNbCoef,double ***_pdblReal);
int (* getAllocatedMatrixOfComplexPoly) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int **_piNbCoef,double ***_pdblReal,double ***_pdblImg);
int (* getAllocatedNamedMatrixOfPoly) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int **_piNbCoef,double ***_pdblReal);
int (* getAllocatedNamedMatrixOfComplexPoly) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int **_piNbCoef,double ***_pdblReal,double ***_pdblImg);
void (* freeAllocatedSinglePoly) (double *_pdblReal);
void (* freeAllocatedSingleComplexPoly) (double *_pdblReal,double *_pdblImg);
void (* freeAllocatedMatrixOfPoly) (int _iRows,int _iCols,int *_piNbCoef,double **_pdblReal);
void (* freeAllocatedMatrixOfComplexPoly) (int _iRows,int _iCols,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
SciErr (* getSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal);
SciErr (* getComplexSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal,double **_pdblImg);
SciErr (* allocSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal);
SciErr (* allocComplexSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal,double **_pdblImg);
SciErr (* createSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal);
SciErr (* createComplexSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal,double const *_pdblImg);
SciErr (* createNamedSparseMatrix) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal);
SciErr (* createNamedComplexSparseMatrix) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal,double const *_pdblImg);
SciErr (* readNamedSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos,double *_pdblReal);
SciErr (* readNamedComplexSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos,double *_pdblReal,double *_pdblImg);
int (* isSparseType) (void *_pvCtx,int *_piAddress);
int (* isNamedSparseType) (void *_pvCtx,char const *_pstName);
int (* getAllocatedSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal);
int (* getAllocatedComplexSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal,double **_pdblImg);
int (* getNamedAllocatedSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal);
int (* getNamedAllocatedComplexSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal,double **_pdblImg);
void (* freeAllocatedSparseMatrix) (int *_piNbItemRows,int *_piColPos,double *_pdblReal);
void (* freeAllocatedComplexSparseMatrix) (int *_piNbItemRows,int *_piColPos,double *_pdblReal,double *_pdblImg);
SciErr (* getMatrixOfBoolean) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int **_piBool);
SciErr (* allocMatrixOfBoolean) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int **_piBool);
SciErr (* createMatrixOfBoolean) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int const *_piBool);
SciErr (* createNamedMatrixOfBoolean) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,int const *_piBool);
SciErr (* readNamedMatrixOfBoolean) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piBool);
int (* isBooleanType) (void *_pvCtx,int *_piAddress);
int (* isNamedBooleanType) (void *_pvCtx,char const *_pstName);
int (* getScalarBoolean) (void *_pvCtx,int *_piAddress,int *_piBool);
int (* getNamedScalarBoolean) (void *_pvCtx,char const *_pstName,int *_piBool);
int (* createScalarBoolean) (void *_pvCtx,int _iVar,int _iBool);
int (* createNamedScalarBoolean) (void *_pvCtx,char const *_pstName,int _iBool);
SciErr (* getBooleanSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos);
SciErr (* allocBooleanSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int **_piNbItemRow,int **_piColPos);
SciErr (* createBooleanSparseMatrix) (void *_pvCtx,int _iVar,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos);
SciErr (* createNamedBooleanSparseMatrix) (void *_pvCtx,char const *_pstName,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos);
SciErr (* readNamedBooleanSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos);
int (* isBooleanSparseType) (void *_pvCtx,int *_piAddress);
int (* isNamedBooleanSparseType) (void *_pvCtx,char const *_pstName);
int (* getAllocatedBooleanSparseMatrix) (void *_pvCtx,int *_piAddress,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos);
int (* getNamedAllocatedBooleanSparseMatrix) (void *_pvCtx,char const *_pstName,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos);
void (* freeAllocatedBooleanSparse) (int *_piNbItemRow,int *_piColPos);
SciErr (* getPointer) (void *_pvCtx,int *_piAddress,void **_pvPtr);
SciErr (* allocPointer) (void *_pvCtx,int _iVar,void **_pvPtr);
SciErr (* createPointer) (void *_pvCtx,int _iVar,void *_pvPtr);
SciErr (* createNamedPointer) (void *_pvCtx,char const *_pstName,void *_pvPtr);
SciErr (* readNamedPointer) (void *_pvCtx,char const *_pstName,void **_pvPtr);
int (* isPointerType) (void *_pvCtx,int *_piAddress);
int (* isNamedPointerType) (void *_pvCtx,char const *_pstName);
SciErr (* getListItemNumber) (void *_pvCtx,int *_piAddress,int *_piNbItem);
SciErr (* getListItemAddress) (void *_pvCtx,int *_piAddress,int _iItemNum,int **_piItemAddress);
SciErr (* getListInList) (void *_pvCtx,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* getTListInList) (void *_pvCtx,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* getMListInList) (void *_pvCtx,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* getListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* getTListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* getMListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int **_piAddress);
SciErr (* createList) (void *_pvCtx,int _iVar,int _iNbItem,int **_piAddress);
SciErr (* createTList) (void *_pvCtx,int _iVar,int _iNbItem,int **_piAddress);
SciErr (* createMList) (void *_pvCtx,int _iVar,int _iNbItem,int **_piAddress);
SciErr (* createNamedList) (void *_pvCtx,char const *_pstName,int _iNbItem,int **_piAddress);
SciErr (* createNamedTList) (void *_pvCtx,char const *_pstName,int _iNbItem,int **_piAddress);
SciErr (* createNamedMList) (void *_pvCtx,char const *_pstName,int _iNbItem,int **_piAddress);
SciErr (* readNamedList) (void *_pvCtx,char const *_pstName,int *_piNbItem,int **_piAddress);
SciErr (* readNamedTList) (void *_pvCtx,char const *_pstName,int *_piNbItem,int **_piAddress);
SciErr (* readNamedMList) (void *_pvCtx,char const *_pstName,int *_piNbItem,int **_piAddress);
SciErr (* createListInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createTListInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createMListInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createTListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createMListInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iNbItem,int **_piAddress);
SciErr (* createVoidInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos);
SciErr (* createUndefinedInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos);
SciErr (* getMatrixOfDoubleInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,double **_pdblReal);
SciErr (* getComplexMatrixOfDoubleInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,double **_pdblReal,double **_pdblImg);
SciErr (* allocMatrixOfDoubleInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,double **_pdblReal);
SciErr (* allocComplexMatrixOfDoubleInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,double **_pdblReal,double **_pdblImg);
SciErr (* createMatrixOfDoubleInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,double const *_pdblReal);
SciErr (* createComplexMatrixOfDoubleInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,double const *_pdblReal,double const *_pdblImg);
SciErr (* createComplexZMatrixOfDoubleInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,doublecomplex const *_pdblData);
SciErr (* createMatrixOfDoubleInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,double const *_pdblReal);
SciErr (* createComplexMatrixOfDoubleInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,double const *_pdblReal,double const *_pdblImg);
SciErr (* createComplexZMatrixOfDoubleInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,doublecomplex const *_pdblData);
SciErr (* readMatrixOfDoubleInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,double *_pdblReal);
SciErr (* readComplexMatrixOfDoubleInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,double *_pdblReal,double *_pdblImg);
SciErr (* getMatrixOfStringInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piLength,char **_pstStrings);
SciErr (* createMatrixOfStringInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,char const *const *_pstStrings);
SciErr (* createMatrixOfStringInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,char const *const *_pstStrings);
SciErr (* readMatrixOfStringInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piLength,char **_pstStrings);
SciErr (* getMatrixOfBooleanInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int **_piBool);
SciErr (* allocMatrixOfBooleanInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int **_piBool);
SciErr (* createMatrixOfBooleanInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int const *_piBool);
SciErr (* createMatrixOfBooleanInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,int const *_piBool);
SciErr (* readMatrixOfBooleanInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piBool);
SciErr (* getMatrixOfPolyInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal);
SciErr (* getComplexMatrixOfPolyInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
SciErr (* createMatrixOfPolyInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal);
SciErr (* createComplexMatrixOfPolyInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal,double const *const *_pdblImg);
SciErr (* readMatrixOfPolyInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal);
SciErr (* readComplexMatrixOfPolyInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbCoef,double **_pdblReal,double **_pdblImg);
SciErr (* createMatrixOfPolyInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal);
SciErr (* createComplexMatrixOfPolyInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,char *_pstVarName,int _iRows,int _iCols,int const *_piNbCoef,double const *const *_pdblReal,double const *const *_pdblImg);
SciErr (* createMatrixOfInteger8InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,char const *_pcData);
SciErr (* createMatrixOfUnsignedInteger8InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned char const *_pucData);
SciErr (* createMatrixOfInteger16InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,short const *_psData);
SciErr (* createMatrixOfUnsignedInteger16InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned short const *_pusData);
SciErr (* createMatrixOfInteger32InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int const *_piData);
SciErr (* createMatrixOfUnsignedInteger32InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned int const *_puiData);
SciErr (* allocMatrixOfInteger8InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,char **_pcData);
SciErr (* allocMatrixOfUnsignedInteger8InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned char **_pucData);
SciErr (* allocMatrixOfInteger16InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,short **_psData);
SciErr (* allocMatrixOfUnsignedInteger16InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned short **_pusData);
SciErr (* allocMatrixOfInteger32InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int **_piData);
SciErr (* allocMatrixOfUnsignedInteger32InList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned int **_puiData);
SciErr (* getMatrixOfInteger8InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,char **_pcData);
SciErr (* getMatrixOfUnsignedInteger8InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned char **_pucData);
SciErr (* getMatrixOfInteger16InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,short **_psData);
SciErr (* getMatrixOfUnsignedInteger16InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned short **_pusData);
SciErr (* getMatrixOfInteger32InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int **_piData);
SciErr (* getMatrixOfUnsignedInteger32InList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned int **_puiData);
SciErr (* createMatrixOfInteger8InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,char const *_pcData);
SciErr (* createMatrixOfUnsignedInteger8InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned char const *_pucData);
SciErr (* createMatrixOfInteger16InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,short const *_psData);
SciErr (* createMatrixOfUnsignedInteger16InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned short const *_pusData);
SciErr (* createMatrixOfInteger32InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,int const *_piData);
SciErr (* createMatrixOfUnsignedInteger32InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,unsigned int const *_puiData);
SciErr (* readMatrixOfIntger8InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,char *_pcData);
SciErr (* readMatrixOfUnsignedInteger8InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned char *_pucData);
SciErr (* readMatrixOfIntger16InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,short *_psData);
SciErr (* readMatrixOfUnsignedInteger16InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned short *_pusData);
SciErr (* readMatrixOfIntger32InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piData);
SciErr (* readMatrixOfUnsignedInteger32InNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,unsigned int *_puiData);
SciErr (* createSparseMatrixInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal);
SciErr (* createComplexSparseMatrixInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal,double const *_pdblImg);
SciErr (* createSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal);
SciErr (* createComplexSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos,double const *_pdblReal,double const *_pdblImg);
SciErr (* getSparseMatrixInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal);
SciErr (* getComplexSparseMatrixInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos,double **_pdblReal,double **_pdblImg);
SciErr (* readSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos,double *_pdblReal);
SciErr (* readComplexSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos,double *_pdblReal,double *_pdblImg);
SciErr (* createBooleanSparseMatrixInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos);
SciErr (* createBooleanSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int _iRows,int _iCols,int _iNbItem,int const *_piNbItemRow,int const *_piColPos);
SciErr (* getBooleanSparseMatrixInList) (void *_pvCtx,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int **_piNbItemRow,int **_piColPos);
SciErr (* readBooleanSparseMatrixInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,int *_piRows,int *_piCols,int *_piNbItem,int *_piNbItemRow,int *_piColPos);
SciErr (* getPointerInList) (void *_pvCtx,int *_piParent,int _iItemPos,void **_pvPtr);
SciErr (* createPointerInList) (void *_pvCtx,int _iVar,int *_piParent,int _iItemPos,void *_pvPtr);
SciErr (* readPointerInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,void **_pvPtr);
SciErr (* createPointerInNamedList) (void *_pvCtx,char const *_pstName,int *_piParent,int _iItemPos,void *_pvPtr);
int (* isListType) (void *_pvCtx,int *_piAddress);
int (* isNamedListType) (void *_pvCtx,char const *_pstName);
int (* isTListType) (void *_pvCtx,int *_piAddress);
int (* isNamedTListType) (void *_pvCtx,char const *_pstName);
int (* isMListType) (void *_pvCtx,int *_piAddress);
int (* isNamedMListType) (void *_pvCtx,char const *_pstName);
int (* addStackSizeError) (SciErr *_psciErr,char *_pstCaller,int iNeeded);
int (* addErrorMessage) (SciErr *_psciErr,int _iErr,char const *_pstMsg,...);
int (* printError) (SciErr *_psciErr,int _iLastMsg);
char (* getErrorMessage) (SciErr _sciErr);
BOOL (* TerminateScilab) (char *ScilabQuit);
int (* SendScilabJob) (char *job);

void InitScilabFunc(){
	*(void **)&getMatrixOfDouble = SWIGDLL_GETPROC("getMatrixOfDouble");
	*(void **)&getComplexMatrixOfDouble = SWIGDLL_GETPROC("getComplexMatrixOfDouble");
	*(void **)&getComplexZMatrixOfDouble = SWIGDLL_GETPROC("getComplexZMatrixOfDouble");
	*(void **)&allocMatrixOfDouble = SWIGDLL_GETPROC("allocMatrixOfDouble");
	*(void **)&allocComplexMatrixOfDouble = SWIGDLL_GETPROC("allocComplexMatrixOfDouble");
	*(void **)&createMatrixOfDouble = SWIGDLL_GETPROC("createMatrixOfDouble");
	*(void **)&createComplexMatrixOfDouble = SWIGDLL_GETPROC("createComplexMatrixOfDouble");
	*(void **)&createComplexZMatrixOfDouble = SWIGDLL_GETPROC("createComplexZMatrixOfDouble");
	*(void **)&createNamedMatrixOfDouble = SWIGDLL_GETPROC("createNamedMatrixOfDouble");
	*(void **)&createNamedComplexMatrixOfDouble = SWIGDLL_GETPROC("createNamedComplexMatrixOfDouble");
	*(void **)&createNamedComplexZMatrixOfDouble = SWIGDLL_GETPROC("createNamedComplexZMatrixOfDouble");
	*(void **)&readNamedMatrixOfDouble = SWIGDLL_GETPROC("readNamedMatrixOfDouble");
	*(void **)&readNamedComplexMatrixOfDouble = SWIGDLL_GETPROC("readNamedComplexMatrixOfDouble");
	*(void **)&isDoubleType = SWIGDLL_GETPROC("isDoubleType");
	*(void **)&isNamedDoubleType = SWIGDLL_GETPROC("isNamedDoubleType");
	*(void **)&getScalarDouble = SWIGDLL_GETPROC("getScalarDouble");
	*(void **)&getScalarComplexDouble = SWIGDLL_GETPROC("getScalarComplexDouble");
	*(void **)&getNamedScalarDouble = SWIGDLL_GETPROC("getNamedScalarDouble");
	*(void **)&getNamedScalarComplexDouble = SWIGDLL_GETPROC("getNamedScalarComplexDouble");
	*(void **)&createScalarDouble = SWIGDLL_GETPROC("createScalarDouble");
	*(void **)&createScalarComplexDouble = SWIGDLL_GETPROC("createScalarComplexDouble");
	*(void **)&createNamedScalarDouble = SWIGDLL_GETPROC("createNamedScalarDouble");
	*(void **)&createNamedScalarComplexDouble = SWIGDLL_GETPROC("createNamedScalarComplexDouble");
	*(void **)&getMatrixOfString = SWIGDLL_GETPROC("getMatrixOfString");
	*(void **)&getMatrixOfWideString = SWIGDLL_GETPROC("getMatrixOfWideString");
	*(void **)&createMatrixOfString = SWIGDLL_GETPROC("createMatrixOfString");
	*(void **)&createMatrixOfWideString = SWIGDLL_GETPROC("createMatrixOfWideString");
	*(void **)&createNamedMatrixOfString = SWIGDLL_GETPROC("createNamedMatrixOfString");
	*(void **)&createNamedMatrixOfWideString = SWIGDLL_GETPROC("createNamedMatrixOfWideString");
	*(void **)&readNamedMatrixOfString = SWIGDLL_GETPROC("readNamedMatrixOfString");
	*(void **)&readNamedMatrixOfWideString = SWIGDLL_GETPROC("readNamedMatrixOfWideString");
	*(void **)&isStringType = SWIGDLL_GETPROC("isStringType");
	*(void **)&isNamedStringType = SWIGDLL_GETPROC("isNamedStringType");
	*(void **)&getAllocatedSingleString = SWIGDLL_GETPROC("getAllocatedSingleString");
	*(void **)&getAllocatedSingleWideString = SWIGDLL_GETPROC("getAllocatedSingleWideString");
	*(void **)&getAllocatedMatrixOfString = SWIGDLL_GETPROC("getAllocatedMatrixOfString");
	*(void **)&getAllocatedMatrixOfWideString = SWIGDLL_GETPROC("getAllocatedMatrixOfWideString");
	*(void **)&getAllocatedNamedSingleString = SWIGDLL_GETPROC("getAllocatedNamedSingleString");
	*(void **)&getAllocatedNamedSingleWideString = SWIGDLL_GETPROC("getAllocatedNamedSingleWideString");
	*(void **)&getAllocatedNamedMatrixOfString = SWIGDLL_GETPROC("getAllocatedNamedMatrixOfString");
	*(void **)&getAllocatedNamedMatrixOfWideString = SWIGDLL_GETPROC("getAllocatedNamedMatrixOfWideString");
	*(void **)&createSingleString = SWIGDLL_GETPROC("createSingleString");
	*(void **)&createSingleWideString = SWIGDLL_GETPROC("createSingleWideString");
	*(void **)&createNamedSingleString = SWIGDLL_GETPROC("createNamedSingleString");
	*(void **)&createNamedSingleWideString = SWIGDLL_GETPROC("createNamedSingleWideString");
	*(void **)&freeAllocatedSingleString = SWIGDLL_GETPROC("freeAllocatedSingleString");
	*(void **)&freeAllocatedSingleWideString = SWIGDLL_GETPROC("freeAllocatedSingleWideString");
	*(void **)&freeAllocatedMatrixOfString = SWIGDLL_GETPROC("freeAllocatedMatrixOfString");
	*(void **)&freeAllocatedMatrixOfWideString = SWIGDLL_GETPROC("freeAllocatedMatrixOfWideString");
	*(void **)&getMatrixOfIntegerPrecision = SWIGDLL_GETPROC("getMatrixOfIntegerPrecision");
	*(void **)&getMatrixOfInteger8 = SWIGDLL_GETPROC("getMatrixOfInteger8");
	*(void **)&getMatrixOfUnsignedInteger8 = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger8");
	*(void **)&getMatrixOfInteger16 = SWIGDLL_GETPROC("getMatrixOfInteger16");
	*(void **)&getMatrixOfUnsignedInteger16 = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger16");
	*(void **)&getMatrixOfInteger32 = SWIGDLL_GETPROC("getMatrixOfInteger32");
	*(void **)&getMatrixOfUnsignedInteger32 = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger32");
	*(void **)&createMatrixOfInteger8 = SWIGDLL_GETPROC("createMatrixOfInteger8");
	*(void **)&createMatrixOfUnsignedInteger8 = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger8");
	*(void **)&createMatrixOfInteger16 = SWIGDLL_GETPROC("createMatrixOfInteger16");
	*(void **)&createMatrixOfUnsignedInteger16 = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger16");
	*(void **)&createMatrixOfInteger32 = SWIGDLL_GETPROC("createMatrixOfInteger32");
	*(void **)&createMatrixOfUnsignedInteger32 = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger32");
	*(void **)&createNamedMatrixOfInteger8 = SWIGDLL_GETPROC("createNamedMatrixOfInteger8");
	*(void **)&createNamedMatrixOfUnsignedInteger8 = SWIGDLL_GETPROC("createNamedMatrixOfUnsignedInteger8");
	*(void **)&createNamedMatrixOfInteger16 = SWIGDLL_GETPROC("createNamedMatrixOfInteger16");
	*(void **)&createNamedMatrixOfUnsignedInteger16 = SWIGDLL_GETPROC("createNamedMatrixOfUnsignedInteger16");
	*(void **)&createNamedMatrixOfInteger32 = SWIGDLL_GETPROC("createNamedMatrixOfInteger32");
	*(void **)&createNamedMatrixOfUnsignedInteger32 = SWIGDLL_GETPROC("createNamedMatrixOfUnsignedInteger32");
	*(void **)&allocMatrixOfInteger8 = SWIGDLL_GETPROC("allocMatrixOfInteger8");
	*(void **)&allocMatrixOfUnsignedInteger8 = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger8");
	*(void **)&allocMatrixOfInteger16 = SWIGDLL_GETPROC("allocMatrixOfInteger16");
	*(void **)&allocMatrixOfUnsignedInteger16 = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger16");
	*(void **)&allocMatrixOfInteger32 = SWIGDLL_GETPROC("allocMatrixOfInteger32");
	*(void **)&allocMatrixOfUnsignedInteger32 = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger32");
	*(void **)&getNamedMatrixOfIntegerPrecision = SWIGDLL_GETPROC("getNamedMatrixOfIntegerPrecision");
	*(void **)&readNamedMatrixOfInteger8 = SWIGDLL_GETPROC("readNamedMatrixOfInteger8");
	*(void **)&readNamedMatrixOfUnsignedInteger8 = SWIGDLL_GETPROC("readNamedMatrixOfUnsignedInteger8");
	*(void **)&readNamedMatrixOfInteger16 = SWIGDLL_GETPROC("readNamedMatrixOfInteger16");
	*(void **)&readNamedMatrixOfUnsignedInteger16 = SWIGDLL_GETPROC("readNamedMatrixOfUnsignedInteger16");
	*(void **)&readNamedMatrixOfInteger32 = SWIGDLL_GETPROC("readNamedMatrixOfInteger32");
	*(void **)&readNamedMatrixOfUnsignedInteger32 = SWIGDLL_GETPROC("readNamedMatrixOfUnsignedInteger32");
	*(void **)&isIntegerType = SWIGDLL_GETPROC("isIntegerType");
	*(void **)&isNamedIntegerType = SWIGDLL_GETPROC("isNamedIntegerType");
	*(void **)&getScalarInteger8 = SWIGDLL_GETPROC("getScalarInteger8");
	*(void **)&getScalarUnsignedInteger8 = SWIGDLL_GETPROC("getScalarUnsignedInteger8");
	*(void **)&getScalarInteger16 = SWIGDLL_GETPROC("getScalarInteger16");
	*(void **)&getScalarUnsignedInteger16 = SWIGDLL_GETPROC("getScalarUnsignedInteger16");
	*(void **)&getScalarInteger32 = SWIGDLL_GETPROC("getScalarInteger32");
	*(void **)&getScalarUnsignedInteger32 = SWIGDLL_GETPROC("getScalarUnsignedInteger32");
	*(void **)&getNamedScalarInteger8 = SWIGDLL_GETPROC("getNamedScalarInteger8");
	*(void **)&getNamedScalarUnsignedInteger8 = SWIGDLL_GETPROC("getNamedScalarUnsignedInteger8");
	*(void **)&getNamedScalarInteger16 = SWIGDLL_GETPROC("getNamedScalarInteger16");
	*(void **)&getNamedScalarUnsignedInteger16 = SWIGDLL_GETPROC("getNamedScalarUnsignedInteger16");
	*(void **)&getNamedScalarInteger32 = SWIGDLL_GETPROC("getNamedScalarInteger32");
	*(void **)&getNamedScalarUnsignedInteger32 = SWIGDLL_GETPROC("getNamedScalarUnsignedInteger32");
	*(void **)&createScalarInteger8 = SWIGDLL_GETPROC("createScalarInteger8");
	*(void **)&createScalarUnsignedInteger8 = SWIGDLL_GETPROC("createScalarUnsignedInteger8");
	*(void **)&createScalarInteger16 = SWIGDLL_GETPROC("createScalarInteger16");
	*(void **)&createScalarUnsignedInteger16 = SWIGDLL_GETPROC("createScalarUnsignedInteger16");
	*(void **)&createScalarInteger32 = SWIGDLL_GETPROC("createScalarInteger32");
	*(void **)&createScalarUnsignedInteger32 = SWIGDLL_GETPROC("createScalarUnsignedInteger32");
	*(void **)&createNamedScalarInteger8 = SWIGDLL_GETPROC("createNamedScalarInteger8");
	*(void **)&createNamedScalarUnsignedInteger8 = SWIGDLL_GETPROC("createNamedScalarUnsignedInteger8");
	*(void **)&createNamedScalarInteger16 = SWIGDLL_GETPROC("createNamedScalarInteger16");
	*(void **)&createNamedScalarUnsignedInteger16 = SWIGDLL_GETPROC("createNamedScalarUnsignedInteger16");
	*(void **)&createNamedScalarInteger32 = SWIGDLL_GETPROC("createNamedScalarInteger32");
	*(void **)&createNamedScalarUnsignedInteger32 = SWIGDLL_GETPROC("createNamedScalarUnsignedInteger32");
	*(void **)&getPolyVariableName = SWIGDLL_GETPROC("getPolyVariableName");
	*(void **)&getMatrixOfPoly = SWIGDLL_GETPROC("getMatrixOfPoly");
	*(void **)&getComplexMatrixOfPoly = SWIGDLL_GETPROC("getComplexMatrixOfPoly");
	*(void **)&createMatrixOfPoly = SWIGDLL_GETPROC("createMatrixOfPoly");
	*(void **)&createComplexMatrixOfPoly = SWIGDLL_GETPROC("createComplexMatrixOfPoly");
	*(void **)&createNamedMatrixOfPoly = SWIGDLL_GETPROC("createNamedMatrixOfPoly");
	*(void **)&createNamedComplexMatrixOfPoly = SWIGDLL_GETPROC("createNamedComplexMatrixOfPoly");
	*(void **)&readNamedMatrixOfPoly = SWIGDLL_GETPROC("readNamedMatrixOfPoly");
	*(void **)&readNamedComplexMatrixOfPoly = SWIGDLL_GETPROC("readNamedComplexMatrixOfPoly");
	*(void **)&isPolyType = SWIGDLL_GETPROC("isPolyType");
	*(void **)&isNamedPolyType = SWIGDLL_GETPROC("isNamedPolyType");
	*(void **)&getAllocatedSinglePoly = SWIGDLL_GETPROC("getAllocatedSinglePoly");
	*(void **)&getAllocatedSingleComplexPoly = SWIGDLL_GETPROC("getAllocatedSingleComplexPoly");
	*(void **)&getAllocatedNamedSinglePoly = SWIGDLL_GETPROC("getAllocatedNamedSinglePoly");
	*(void **)&getAllocatedNamedSingleComplexPoly = SWIGDLL_GETPROC("getAllocatedNamedSingleComplexPoly");
	*(void **)&getAllocatedMatrixOfPoly = SWIGDLL_GETPROC("getAllocatedMatrixOfPoly");
	*(void **)&getAllocatedMatrixOfComplexPoly = SWIGDLL_GETPROC("getAllocatedMatrixOfComplexPoly");
	*(void **)&getAllocatedNamedMatrixOfPoly = SWIGDLL_GETPROC("getAllocatedNamedMatrixOfPoly");
	*(void **)&getAllocatedNamedMatrixOfComplexPoly = SWIGDLL_GETPROC("getAllocatedNamedMatrixOfComplexPoly");
	*(void **)&freeAllocatedSinglePoly = SWIGDLL_GETPROC("freeAllocatedSinglePoly");
	*(void **)&freeAllocatedSingleComplexPoly = SWIGDLL_GETPROC("freeAllocatedSingleComplexPoly");
	*(void **)&freeAllocatedMatrixOfPoly = SWIGDLL_GETPROC("freeAllocatedMatrixOfPoly");
	*(void **)&freeAllocatedMatrixOfComplexPoly = SWIGDLL_GETPROC("freeAllocatedMatrixOfComplexPoly");
	*(void **)&getSparseMatrix = SWIGDLL_GETPROC("getSparseMatrix");
	*(void **)&getComplexSparseMatrix = SWIGDLL_GETPROC("getComplexSparseMatrix");
	*(void **)&allocSparseMatrix = SWIGDLL_GETPROC("allocSparseMatrix");
	*(void **)&allocComplexSparseMatrix = SWIGDLL_GETPROC("allocComplexSparseMatrix");
	*(void **)&createSparseMatrix = SWIGDLL_GETPROC("createSparseMatrix");
	*(void **)&createComplexSparseMatrix = SWIGDLL_GETPROC("createComplexSparseMatrix");
	*(void **)&createNamedSparseMatrix = SWIGDLL_GETPROC("createNamedSparseMatrix");
	*(void **)&createNamedComplexSparseMatrix = SWIGDLL_GETPROC("createNamedComplexSparseMatrix");
	*(void **)&readNamedSparseMatrix = SWIGDLL_GETPROC("readNamedSparseMatrix");
	*(void **)&readNamedComplexSparseMatrix = SWIGDLL_GETPROC("readNamedComplexSparseMatrix");
	*(void **)&isSparseType = SWIGDLL_GETPROC("isSparseType");
	*(void **)&isNamedSparseType = SWIGDLL_GETPROC("isNamedSparseType");
	*(void **)&getAllocatedSparseMatrix = SWIGDLL_GETPROC("getAllocatedSparseMatrix");
	*(void **)&getAllocatedComplexSparseMatrix = SWIGDLL_GETPROC("getAllocatedComplexSparseMatrix");
	*(void **)&getNamedAllocatedSparseMatrix = SWIGDLL_GETPROC("getNamedAllocatedSparseMatrix");
	*(void **)&getNamedAllocatedComplexSparseMatrix = SWIGDLL_GETPROC("getNamedAllocatedComplexSparseMatrix");
	*(void **)&freeAllocatedSparseMatrix = SWIGDLL_GETPROC("freeAllocatedSparseMatrix");
	*(void **)&freeAllocatedComplexSparseMatrix = SWIGDLL_GETPROC("freeAllocatedComplexSparseMatrix");
	*(void **)&getMatrixOfBoolean = SWIGDLL_GETPROC("getMatrixOfBoolean");
	*(void **)&allocMatrixOfBoolean = SWIGDLL_GETPROC("allocMatrixOfBoolean");
	*(void **)&createMatrixOfBoolean = SWIGDLL_GETPROC("createMatrixOfBoolean");
	*(void **)&createNamedMatrixOfBoolean = SWIGDLL_GETPROC("createNamedMatrixOfBoolean");
	*(void **)&readNamedMatrixOfBoolean = SWIGDLL_GETPROC("readNamedMatrixOfBoolean");
	*(void **)&isBooleanType = SWIGDLL_GETPROC("isBooleanType");
	*(void **)&isNamedBooleanType = SWIGDLL_GETPROC("isNamedBooleanType");
	*(void **)&getScalarBoolean = SWIGDLL_GETPROC("getScalarBoolean");
	*(void **)&getNamedScalarBoolean = SWIGDLL_GETPROC("getNamedScalarBoolean");
	*(void **)&createScalarBoolean = SWIGDLL_GETPROC("createScalarBoolean");
	*(void **)&createNamedScalarBoolean = SWIGDLL_GETPROC("createNamedScalarBoolean");
	*(void **)&getBooleanSparseMatrix = SWIGDLL_GETPROC("getBooleanSparseMatrix");
	*(void **)&allocBooleanSparseMatrix = SWIGDLL_GETPROC("allocBooleanSparseMatrix");
	*(void **)&createBooleanSparseMatrix = SWIGDLL_GETPROC("createBooleanSparseMatrix");
	*(void **)&createNamedBooleanSparseMatrix = SWIGDLL_GETPROC("createNamedBooleanSparseMatrix");
	*(void **)&readNamedBooleanSparseMatrix = SWIGDLL_GETPROC("readNamedBooleanSparseMatrix");
	*(void **)&isBooleanSparseType = SWIGDLL_GETPROC("isBooleanSparseType");
	*(void **)&isNamedBooleanSparseType = SWIGDLL_GETPROC("isNamedBooleanSparseType");
	*(void **)&getAllocatedBooleanSparseMatrix = SWIGDLL_GETPROC("getAllocatedBooleanSparseMatrix");
	*(void **)&getNamedAllocatedBooleanSparseMatrix = SWIGDLL_GETPROC("getNamedAllocatedBooleanSparseMatrix");
	*(void **)&freeAllocatedBooleanSparse = SWIGDLL_GETPROC("freeAllocatedBooleanSparse");
	*(void **)&getPointer = SWIGDLL_GETPROC("getPointer");
	*(void **)&allocPointer = SWIGDLL_GETPROC("allocPointer");
	*(void **)&createPointer = SWIGDLL_GETPROC("createPointer");
	*(void **)&createNamedPointer = SWIGDLL_GETPROC("createNamedPointer");
	*(void **)&readNamedPointer = SWIGDLL_GETPROC("readNamedPointer");
	*(void **)&isPointerType = SWIGDLL_GETPROC("isPointerType");
	*(void **)&isNamedPointerType = SWIGDLL_GETPROC("isNamedPointerType");
	*(void **)&getListItemNumber = SWIGDLL_GETPROC("getListItemNumber");
	*(void **)&getListItemAddress = SWIGDLL_GETPROC("getListItemAddress");
	*(void **)&getListInList = SWIGDLL_GETPROC("getListInList");
	*(void **)&getTListInList = SWIGDLL_GETPROC("getTListInList");
	*(void **)&getMListInList = SWIGDLL_GETPROC("getMListInList");
	*(void **)&getListInNamedList = SWIGDLL_GETPROC("getListInNamedList");
	*(void **)&getTListInNamedList = SWIGDLL_GETPROC("getTListInNamedList");
	*(void **)&getMListInNamedList = SWIGDLL_GETPROC("getMListInNamedList");
	*(void **)&createList = SWIGDLL_GETPROC("createList");
	*(void **)&createTList = SWIGDLL_GETPROC("createTList");
	*(void **)&createMList = SWIGDLL_GETPROC("createMList");
	*(void **)&createNamedList = SWIGDLL_GETPROC("createNamedList");
	*(void **)&createNamedTList = SWIGDLL_GETPROC("createNamedTList");
	*(void **)&createNamedMList = SWIGDLL_GETPROC("createNamedMList");
	*(void **)&readNamedList = SWIGDLL_GETPROC("readNamedList");
	*(void **)&readNamedTList = SWIGDLL_GETPROC("readNamedTList");
	*(void **)&readNamedMList = SWIGDLL_GETPROC("readNamedMList");
	*(void **)&createListInList = SWIGDLL_GETPROC("createListInList");
	*(void **)&createTListInList = SWIGDLL_GETPROC("createTListInList");
	*(void **)&createMListInList = SWIGDLL_GETPROC("createMListInList");
	*(void **)&createListInNamedList = SWIGDLL_GETPROC("createListInNamedList");
	*(void **)&createTListInNamedList = SWIGDLL_GETPROC("createTListInNamedList");
	*(void **)&createMListInNamedList = SWIGDLL_GETPROC("createMListInNamedList");
	*(void **)&createVoidInNamedList = SWIGDLL_GETPROC("createVoidInNamedList");
	*(void **)&createUndefinedInNamedList = SWIGDLL_GETPROC("createUndefinedInNamedList");
	*(void **)&getMatrixOfDoubleInList = SWIGDLL_GETPROC("getMatrixOfDoubleInList");
	*(void **)&getComplexMatrixOfDoubleInList = SWIGDLL_GETPROC("getComplexMatrixOfDoubleInList");
	*(void **)&allocMatrixOfDoubleInList = SWIGDLL_GETPROC("allocMatrixOfDoubleInList");
	*(void **)&allocComplexMatrixOfDoubleInList = SWIGDLL_GETPROC("allocComplexMatrixOfDoubleInList");
	*(void **)&createMatrixOfDoubleInList = SWIGDLL_GETPROC("createMatrixOfDoubleInList");
	*(void **)&createComplexMatrixOfDoubleInList = SWIGDLL_GETPROC("createComplexMatrixOfDoubleInList");
	*(void **)&createComplexZMatrixOfDoubleInList = SWIGDLL_GETPROC("createComplexZMatrixOfDoubleInList");
	*(void **)&createMatrixOfDoubleInNamedList = SWIGDLL_GETPROC("createMatrixOfDoubleInNamedList");
	*(void **)&createComplexMatrixOfDoubleInNamedList = SWIGDLL_GETPROC("createComplexMatrixOfDoubleInNamedList");
	*(void **)&createComplexZMatrixOfDoubleInNamedList = SWIGDLL_GETPROC("createComplexZMatrixOfDoubleInNamedList");
	*(void **)&readMatrixOfDoubleInNamedList = SWIGDLL_GETPROC("readMatrixOfDoubleInNamedList");
	*(void **)&readComplexMatrixOfDoubleInNamedList = SWIGDLL_GETPROC("readComplexMatrixOfDoubleInNamedList");
	*(void **)&getMatrixOfStringInList = SWIGDLL_GETPROC("getMatrixOfStringInList");
	*(void **)&createMatrixOfStringInList = SWIGDLL_GETPROC("createMatrixOfStringInList");
	*(void **)&createMatrixOfStringInNamedList = SWIGDLL_GETPROC("createMatrixOfStringInNamedList");
	*(void **)&readMatrixOfStringInNamedList = SWIGDLL_GETPROC("readMatrixOfStringInNamedList");
	*(void **)&getMatrixOfBooleanInList = SWIGDLL_GETPROC("getMatrixOfBooleanInList");
	*(void **)&allocMatrixOfBooleanInList = SWIGDLL_GETPROC("allocMatrixOfBooleanInList");
	*(void **)&createMatrixOfBooleanInList = SWIGDLL_GETPROC("createMatrixOfBooleanInList");
	*(void **)&createMatrixOfBooleanInNamedList = SWIGDLL_GETPROC("createMatrixOfBooleanInNamedList");
	*(void **)&readMatrixOfBooleanInNamedList = SWIGDLL_GETPROC("readMatrixOfBooleanInNamedList");
	*(void **)&getMatrixOfPolyInList = SWIGDLL_GETPROC("getMatrixOfPolyInList");
	*(void **)&getComplexMatrixOfPolyInList = SWIGDLL_GETPROC("getComplexMatrixOfPolyInList");
	*(void **)&createMatrixOfPolyInList = SWIGDLL_GETPROC("createMatrixOfPolyInList");
	*(void **)&createComplexMatrixOfPolyInList = SWIGDLL_GETPROC("createComplexMatrixOfPolyInList");
	*(void **)&readMatrixOfPolyInNamedList = SWIGDLL_GETPROC("readMatrixOfPolyInNamedList");
	*(void **)&readComplexMatrixOfPolyInNamedList = SWIGDLL_GETPROC("readComplexMatrixOfPolyInNamedList");
	*(void **)&createMatrixOfPolyInNamedList = SWIGDLL_GETPROC("createMatrixOfPolyInNamedList");
	*(void **)&createComplexMatrixOfPolyInNamedList = SWIGDLL_GETPROC("createComplexMatrixOfPolyInNamedList");
	*(void **)&createMatrixOfInteger8InList = SWIGDLL_GETPROC("createMatrixOfInteger8InList");
	*(void **)&createMatrixOfUnsignedInteger8InList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger8InList");
	*(void **)&createMatrixOfInteger16InList = SWIGDLL_GETPROC("createMatrixOfInteger16InList");
	*(void **)&createMatrixOfUnsignedInteger16InList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger16InList");
	*(void **)&createMatrixOfInteger32InList = SWIGDLL_GETPROC("createMatrixOfInteger32InList");
	*(void **)&createMatrixOfUnsignedInteger32InList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger32InList");
	*(void **)&allocMatrixOfInteger8InList = SWIGDLL_GETPROC("allocMatrixOfInteger8InList");
	*(void **)&allocMatrixOfUnsignedInteger8InList = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger8InList");
	*(void **)&allocMatrixOfInteger16InList = SWIGDLL_GETPROC("allocMatrixOfInteger16InList");
	*(void **)&allocMatrixOfUnsignedInteger16InList = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger16InList");
	*(void **)&allocMatrixOfInteger32InList = SWIGDLL_GETPROC("allocMatrixOfInteger32InList");
	*(void **)&allocMatrixOfUnsignedInteger32InList = SWIGDLL_GETPROC("allocMatrixOfUnsignedInteger32InList");
	*(void **)&getMatrixOfInteger8InList = SWIGDLL_GETPROC("getMatrixOfInteger8InList");
	*(void **)&getMatrixOfUnsignedInteger8InList = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger8InList");
	*(void **)&getMatrixOfInteger16InList = SWIGDLL_GETPROC("getMatrixOfInteger16InList");
	*(void **)&getMatrixOfUnsignedInteger16InList = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger16InList");
	*(void **)&getMatrixOfInteger32InList = SWIGDLL_GETPROC("getMatrixOfInteger32InList");
	*(void **)&getMatrixOfUnsignedInteger32InList = SWIGDLL_GETPROC("getMatrixOfUnsignedInteger32InList");
	*(void **)&createMatrixOfInteger8InNamedList = SWIGDLL_GETPROC("createMatrixOfInteger8InNamedList");
	*(void **)&createMatrixOfUnsignedInteger8InNamedList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger8InNamedList");
	*(void **)&createMatrixOfInteger16InNamedList = SWIGDLL_GETPROC("createMatrixOfInteger16InNamedList");
	*(void **)&createMatrixOfUnsignedInteger16InNamedList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger16InNamedList");
	*(void **)&createMatrixOfInteger32InNamedList = SWIGDLL_GETPROC("createMatrixOfInteger32InNamedList");
	*(void **)&createMatrixOfUnsignedInteger32InNamedList = SWIGDLL_GETPROC("createMatrixOfUnsignedInteger32InNamedList");
	*(void **)&readMatrixOfIntger8InNamedList = SWIGDLL_GETPROC("readMatrixOfIntger8InNamedList");
	*(void **)&readMatrixOfUnsignedInteger8InNamedList = SWIGDLL_GETPROC("readMatrixOfUnsignedInteger8InNamedList");
	*(void **)&readMatrixOfIntger16InNamedList = SWIGDLL_GETPROC("readMatrixOfIntger16InNamedList");
	*(void **)&readMatrixOfUnsignedInteger16InNamedList = SWIGDLL_GETPROC("readMatrixOfUnsignedInteger16InNamedList");
	*(void **)&readMatrixOfIntger32InNamedList = SWIGDLL_GETPROC("readMatrixOfIntger32InNamedList");
	*(void **)&readMatrixOfUnsignedInteger32InNamedList = SWIGDLL_GETPROC("readMatrixOfUnsignedInteger32InNamedList");
	*(void **)&createSparseMatrixInList = SWIGDLL_GETPROC("createSparseMatrixInList");
	*(void **)&createComplexSparseMatrixInList = SWIGDLL_GETPROC("createComplexSparseMatrixInList");
	*(void **)&createSparseMatrixInNamedList = SWIGDLL_GETPROC("createSparseMatrixInNamedList");
	*(void **)&createComplexSparseMatrixInNamedList = SWIGDLL_GETPROC("createComplexSparseMatrixInNamedList");
	*(void **)&getSparseMatrixInList = SWIGDLL_GETPROC("getSparseMatrixInList");
	*(void **)&getComplexSparseMatrixInList = SWIGDLL_GETPROC("getComplexSparseMatrixInList");
	*(void **)&readSparseMatrixInNamedList = SWIGDLL_GETPROC("readSparseMatrixInNamedList");
	*(void **)&readComplexSparseMatrixInNamedList = SWIGDLL_GETPROC("readComplexSparseMatrixInNamedList");
	*(void **)&createBooleanSparseMatrixInList = SWIGDLL_GETPROC("createBooleanSparseMatrixInList");
	*(void **)&createBooleanSparseMatrixInNamedList = SWIGDLL_GETPROC("createBooleanSparseMatrixInNamedList");
	*(void **)&getBooleanSparseMatrixInList = SWIGDLL_GETPROC("getBooleanSparseMatrixInList");
	*(void **)&readBooleanSparseMatrixInNamedList = SWIGDLL_GETPROC("readBooleanSparseMatrixInNamedList");
	*(void **)&getPointerInList = SWIGDLL_GETPROC("getPointerInList");
	*(void **)&createPointerInList = SWIGDLL_GETPROC("createPointerInList");
	*(void **)&readPointerInNamedList = SWIGDLL_GETPROC("readPointerInNamedList");
	*(void **)&createPointerInNamedList = SWIGDLL_GETPROC("createPointerInNamedList");
	*(void **)&isListType = SWIGDLL_GETPROC("isListType");
	*(void **)&isNamedListType = SWIGDLL_GETPROC("isNamedListType");
	*(void **)&isTListType = SWIGDLL_GETPROC("isTListType");
	*(void **)&isNamedTListType = SWIGDLL_GETPROC("isNamedTListType");
	*(void **)&isMListType = SWIGDLL_GETPROC("isMListType");
	*(void **)&isNamedMListType = SWIGDLL_GETPROC("isNamedMListType");
	*(void **)&addStackSizeError = SWIGDLL_GETPROC("addStackSizeError");
	*(void **)&addErrorMessage = SWIGDLL_GETPROC("addErrorMessage");
	*(void **)&printError = SWIGDLL_GETPROC("printError");
	*(void **)&getErrorMessage = SWIGDLL_GETPROC("getErrorMessage");
	*(void **)&TerminateScilab = SWIGDLL_GETPROC("TerminateScilab");
	*(void **)&SendScilabJob = SWIGDLL_GETPROC("SendScilabJob");
}
