// *** AUTOMATICALLY CREATED ***                                  
// *** DO NOT EDIT THIS FILE ***                                  
// Python Version for Embedding                                   
#define EMB_PYTHON_VER 34                               
#define PYTHON_H_REL  "../../include/Python/Python.h" 
#define PYTHON_H_PATH <Python/Python.h>             
